// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsAyoVGFdn9x33MOdhewQ7no6JMVk05ms',
    appId: '1:1086669432559:web:6a916da9fb9d275da7dd1a',
    messagingSenderId: '1086669432559',
    projectId: 'lifequestplatinum',
    authDomain: 'lifequestplatinum.firebaseapp.com',
    storageBucket: 'lifequestplatinum.firebasestorage.app',
    measurementId: 'G-F21E9N58K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8BiaB2kPmOwXDZOMxRho2FHLIGonk5ZU',
    appId: '1:1086669432559:android:351d852bf53ba48ea7dd1a',
    messagingSenderId: '1086669432559',
    projectId: 'lifequestplatinum',
    storageBucket: 'lifequestplatinum.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWpZFoYs-oiLJx3wJrMvK45A-Yk3f_Po8',
    appId: '1:1086669432559:ios:ac6521649e8f156fa7dd1a',
    messagingSenderId: '1086669432559',
    projectId: 'lifequestplatinum',
    storageBucket: 'lifequestplatinum.firebasestorage.app',
    iosBundleId: 'com.example.lifequest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWpZFoYs-oiLJx3wJrMvK45A-Yk3f_Po8',
    appId: '1:1086669432559:ios:ac6521649e8f156fa7dd1a',
    messagingSenderId: '1086669432559',
    projectId: 'lifequestplatinum',
    storageBucket: 'lifequestplatinum.firebasestorage.app',
    iosBundleId: 'com.example.lifequest1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsAyoVGFdn9x33MOdhewQ7no6JMVk05ms',
    appId: '1:1086669432559:web:fa05912e7452588da7dd1a',
    messagingSenderId: '1086669432559',
    projectId: 'lifequestplatinum',
    authDomain: 'lifequestplatinum.firebaseapp.com',
    storageBucket: 'lifequestplatinum.firebasestorage.app',
    measurementId: 'G-82S008CYBS',
  );
}
